# =============================================================================
# HOMEPAGE DOCKER CONFIGURATION
# =============================================================================
---
homeserver:
  socket: /var/run/docker.sock
