# =============================================================================
# HOMEPAGE SETTINGS
# =============================================================================
---
title: Home Server
background:
  image: https://images.unsplash.com/photo-1502791451862-7bd8c1df43a7?auto=format&fit=crop&w=1920&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

theme: dark
color: slate

headerStyle: boxed

layout:
  Media:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 5
  Photos:
    style: row
    columns: 1
  Home:
    style: row
    columns: 2
  Utilities:
    style: row
    columns: 3
  System:
    style: row
    columns: 2
